sudo: required
dist: trusty

language: go

go:
- 1.7
#- tip

cache:
  directories:
  - ~/.platformio

addons:
  apt:
    packages:
    - libi2c-dev
    - gcc-arm-linux-gnueabi
    - libc6-dev-armel-cross
    # shellcheck is not in Travis' Ubuntu
    #- shellcheck
  ssh_known_hosts:
  # Keep in sync with bin/deploy.
  - rover.dasfoo.org:31438
  - fb.rover.dasfoo.org:31438

install:
- pip install --user --upgrade platformio
- platformio lib --global install 19 580 # Adafruit-DHT, EasyVR
- platformio lib --global update

script:
- ssh -p 31438 pi@fb.rover.dasfoo.org pwd
# Raspberry Pi part
- eval "$(curl https://raw.githubusercontent.com/dasfoo/travis/master/install-protoc.sh)"
- curl https://raw.githubusercontent.com/dasfoo/travis/master/go.sh | sh
# Common arduino part
- curl https://raw.githubusercontent.com/dasfoo/travis/master/cpp.sh | sh -s bb/* mc/*
- export PLATFORMIO_BUILD_FLAGS="-Wall -Werror"
# BotBoarduino part
- platformio ci --board=diecimilaatmega328 bb
# MotorController part
- platformio ci --board=diecimilaatmega328 mc
# Shell part
- curl https://raw.githubusercontent.com/dasfoo/travis/master/shell.sh | sh -s bin/*

before_deploy:
# Generate deploy script
- |
    cat >travis-deploy.sh <<'SHELL'
    set -e
    if [ "${TRAVIS_GO_VERSION?}" != "tip" ]; then
      eval "$(ssh-agent)"
      ssh-add <(tr '|' '\n' <<<"${REMOTE_HOST_LOGIN_KEY?}")

      bin/deploy push
    else
        echo "Not deploying for Go tip build."
    fi

deploy:
  provider: script
  skip_cleanup: true
  script: bash travis-deploy.sh

branches:
  only:
  - master
