language: go
# sad but we need sudo to install libi2c-dev
sudo: required

go:
    - 1.5
    # - release (it's 1.4 for now, and cross-compiling doesn't work too well)
    - tip

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libi2c-dev
    - go get github.com/alecthomas/gometalinter
    - gometalinter --install --update
    - go get github.com/axw/gocov/gocov
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go get -v ./...
    - gometalinter --deadline 1m ./...
    - goveralls -v -service=travis-ci ./...

branches:
    only:
        - master
