language: go

go:
    - 1.5
    # Temporarily disable until Travis CI is fast again
    #- tip

cache:
    directories:
        - ~/.platformio
        - ~/.shellcheck

addons:
    apt:
        packages:
        - libi2c-dev
        # shellcheck is not in Travis' Ubuntu
        #- shellcheck

install:
    # Rapsberry Pi part
    - go get github.com/alecthomas/gometalinter
    - gometalinter --install --update
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/modocache/gover
    - go get github.com/mattn/goveralls
    # BotBoarduino part
    - pip install --user --upgrade platformio
    - platformio lib install 19 580 # Adafruit-DHT, EasyVR
    - mkdir -p ~/.shellcheck
    - curl -Lso ~/.shellcheck/shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.3/shellcheck
    - chmod +x ~/.shellcheck/shellcheck

script:
    # Raspberry Pi part
    - go get -v ./...
    - gometalinter --deadline 1m ./...
    - go test -race -trace ./...
    - gover
    - goveralls -v -coverprofile=gover.coverprofile -service=travis-ci ./...
    # BotBoarduino part
    - platformio ci --board=diecimilaatmega328 bb
    # MotorController part
    - platformio ci --board=diecimilaatmega328 mc
    # Shell part
    - ~/.shellcheck/shellcheck bin/*

branches:
    only:
        - master
